package com.moisat.persistence.entities;
// Generated Aug 30, 2018 5:54:55 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Actor generated by hbm2java
 */
@Entity
@Table(name = "ACTOR", schema = "SATFING")
public class Actor implements java.io.Serializable {

	private long codigoActor;
	private Persona persona;
	private Intervencion intervencion;
	private String tipoactor;

	public Actor() {
	}

	public Actor(long codigoActor, Persona persona, Intervencion intervencion, String tipoactor) {
		this.codigoActor = codigoActor;
		this.persona = persona;
		this.intervencion = intervencion;
		this.tipoactor = tipoactor;
	}

	@Id

	@Column(name = "CODIGO_ACTOR", unique = true, nullable = false, precision = 10, scale = 0)
	public long getCodigoActor() {
		return this.codigoActor;
	}

	public void setCodigoActor(long codigoActor) {
		this.codigoActor = codigoActor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGO_PERSONA", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGO_INTERVENCION", nullable = false)
	public Intervencion getIntervencion() {
		return this.intervencion;
	}

	public void setIntervencion(Intervencion intervencion) {
		this.intervencion = intervencion;
	}

	@Column(name = "TIPOACTOR", nullable = false, length = 40)
	public String getTipoactor() {
		return this.tipoactor;
	}

	public void setTipoactor(String tipoactor) {
		this.tipoactor = tipoactor;
	}

}
