package com.moisat.persistence.entities;
// Generated Sep 1, 2018 11:44:50 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Asignatura generated by hbm2java
 */
@Entity
@Table(name = "ASIGNATURA", schema = "SATFING")
public class Asignatura implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idAsignatura;
	private Departamento departamento;
	private String nombreAsignatura;
	private String componenteCurso;
	private Long creditos;
	private Set<Clase> clases = new HashSet<Clase>(0);

	public Asignatura() {
	}

	public Asignatura(long idAsignatura, Departamento departamento, String nombreAsignatura) {
		this.idAsignatura = idAsignatura;
		this.departamento = departamento;
		this.nombreAsignatura = nombreAsignatura;
	}

	public Asignatura(long idAsignatura, Departamento departamento, String nombreAsignatura, String componenteCurso,
			Long creditos, Set<Clase> clases) {
		this.idAsignatura = idAsignatura;
		this.departamento = departamento;
		this.nombreAsignatura = nombreAsignatura;
		this.componenteCurso = componenteCurso;
		this.creditos = creditos;
		this.clases = clases;
	}

	@Id

	@Column(name = "ID_ASIGNATURA", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdAsignatura() {
		return this.idAsignatura;
	}

	public void setIdAsignatura(long idAsignatura) {
		this.idAsignatura = idAsignatura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_DEPARTAMENTO", nullable = false)
	public Departamento getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	@Column(name = "NOMBRE_ASIGNATURA", nullable = false, length = 510)
	public String getNombreAsignatura() {
		return this.nombreAsignatura;
	}

	public void setNombreAsignatura(String nombreAsignatura) {
		this.nombreAsignatura = nombreAsignatura;
	}

	@Column(name = "COMPONENTE_CURSO", length = 20)
	public String getComponenteCurso() {
		return this.componenteCurso;
	}

	public void setComponenteCurso(String componenteCurso) {
		this.componenteCurso = componenteCurso;
	}

	@Column(name = "CREDITOS", precision = 10, scale = 0)
	public Long getCreditos() {
		return this.creditos;
	}

	public void setCreditos(Long creditos) {
		this.creditos = creditos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "asignatura")
	public Set<Clase> getClases() {
		return this.clases;
	}

	public void setClases(Set<Clase> clases) {
		this.clases = clases;
	}

}
