package com.moisat.persistence.entities;
// Generated Sep 1, 2018 11:44:50 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Carrera generated by hbm2java
 */
@Entity
@Table(name = "CARRERA", schema = "SATFING", uniqueConstraints = {
		@UniqueConstraint(columnNames = "DEPARTAMENTOASOCIADO"), @UniqueConstraint(columnNames = "DIRECTOR") })
public class Carrera implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idCarrera;
	private Facultad facultad;
	private Departamento departamento;
	private Persona persona;
	private String nombreCarrera;
	private Set<CarreraEstudiante> carreraEstudiantes = new HashSet<CarreraEstudiante>(0);

	public Carrera() {
	}

	public Carrera(long idCarrera, Facultad facultad, Departamento departamento, Persona persona,
			String nombreCarrera) {
		this.idCarrera = idCarrera;
		this.facultad = facultad;
		this.departamento = departamento;
		this.persona = persona;
		this.nombreCarrera = nombreCarrera;
	}

	public Carrera(long idCarrera, Facultad facultad, Departamento departamento, Persona persona, String nombreCarrera,
			Set<CarreraEstudiante> carreraEstudiantes) {
		this.idCarrera = idCarrera;
		this.facultad = facultad;
		this.departamento = departamento;
		this.persona = persona;
		this.nombreCarrera = nombreCarrera;
		this.carreraEstudiantes = carreraEstudiantes;
	}

	@Id

	@Column(name = "ID_CARRERA", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdCarrera() {
		return this.idCarrera;
	}

	public void setIdCarrera(long idCarrera) {
		this.idCarrera = idCarrera;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_FACULTAD", nullable = false)
	public Facultad getFacultad() {
		return this.facultad;
	}

	public void setFacultad(Facultad facultad) {
		this.facultad = facultad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEPARTAMENTOASOCIADO", unique = true, nullable = false)
	public Departamento getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DIRECTOR", unique = true, nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "NOMBRE_CARRERA", nullable = false, length = 510)
	public String getNombreCarrera() {
		return this.nombreCarrera;
	}

	public void setNombreCarrera(String nombreCarrera) {
		this.nombreCarrera = nombreCarrera;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "carrera")
	public Set<CarreraEstudiante> getCarreraEstudiantes() {
		return this.carreraEstudiantes;
	}

	public void setCarreraEstudiantes(Set<CarreraEstudiante> carreraEstudiantes) {
		this.carreraEstudiantes = carreraEstudiantes;
	}

}
