package com.moisat.persistence.entities;
// Generated Aug 30, 2018 5:54:55 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CarreraEstudianteId generated by hbm2java
 */
@Embeddable
public class CarreraEstudianteId implements java.io.Serializable {

	private long idCarrera;
	private long codigoEstudiante;

	public CarreraEstudianteId() {
	}

	public CarreraEstudianteId(long idCarrera, long codigoEstudiante) {
		this.idCarrera = idCarrera;
		this.codigoEstudiante = codigoEstudiante;
	}

	@Column(name = "ID_CARRERA", nullable = false, precision = 10, scale = 0)
	public long getIdCarrera() {
		return this.idCarrera;
	}

	public void setIdCarrera(long idCarrera) {
		this.idCarrera = idCarrera;
	}

	@Column(name = "CODIGO_ESTUDIANTE", nullable = false, precision = 15, scale = 0)
	public long getCodigoEstudiante() {
		return this.codigoEstudiante;
	}

	public void setCodigoEstudiante(long codigoEstudiante) {
		this.codigoEstudiante = codigoEstudiante;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CarreraEstudianteId))
			return false;
		CarreraEstudianteId castOther = (CarreraEstudianteId) other;

		return (this.getIdCarrera() == castOther.getIdCarrera())
				&& (this.getCodigoEstudiante() == castOther.getCodigoEstudiante());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdCarrera();
		result = 37 * result + (int) this.getCodigoEstudiante();
		return result;
	}

}
