package com.moisat.persistence.entities;
// Generated Aug 30, 2018 5:54:55 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CarreraEstudiante generated by hbm2java
 */
@Entity
@Table(name = "CARRERA_ESTUDIANTE", schema = "SATFING")
public class CarreraEstudiante implements java.io.Serializable {

	private CarreraEstudianteId id;
	private Carrera carrera;
	private Estudiante estudiante;
	private BigDecimal totalcreditosaprobados;
	private BigDecimal totalcreditoscursados;
	private String situacionacademica;
	private BigDecimal totalcreditosconvalidados;
	private BigDecimal totalcreditosconvalidados2;
	private String estadoprogramaacademico;
	private BigDecimal promedioponderadoacumulado;

	public CarreraEstudiante() {
	}

	public CarreraEstudiante(CarreraEstudianteId id, Carrera carrera, Estudiante estudiante,
			BigDecimal promedioponderadoacumulado) {
		this.id = id;
		this.carrera = carrera;
		this.estudiante = estudiante;
		this.promedioponderadoacumulado = promedioponderadoacumulado;
	}

	public CarreraEstudiante(CarreraEstudianteId id, Carrera carrera, Estudiante estudiante,
			BigDecimal totalcreditosaprobados, BigDecimal totalcreditoscursados, String situacionacademica,
			BigDecimal totalcreditosconvalidados, BigDecimal totalcreditosconvalidados2, String estadoprogramaacademico,
			BigDecimal promedioponderadoacumulado) {
		this.id = id;
		this.carrera = carrera;
		this.estudiante = estudiante;
		this.totalcreditosaprobados = totalcreditosaprobados;
		this.totalcreditoscursados = totalcreditoscursados;
		this.situacionacademica = situacionacademica;
		this.totalcreditosconvalidados = totalcreditosconvalidados;
		this.totalcreditosconvalidados2 = totalcreditosconvalidados2;
		this.estadoprogramaacademico = estadoprogramaacademico;
		this.promedioponderadoacumulado = promedioponderadoacumulado;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idCarrera", column = @Column(name = "ID_CARRERA", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "codigoEstudiante", column = @Column(name = "CODIGO_ESTUDIANTE", nullable = false, precision = 15, scale = 0)) })
	public CarreraEstudianteId getId() {
		return this.id;
	}

	public void setId(CarreraEstudianteId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CARRERA", nullable = false, insertable = false, updatable = false)
	public Carrera getCarrera() {
		return this.carrera;
	}

	public void setCarrera(Carrera carrera) {
		this.carrera = carrera;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGO_ESTUDIANTE", nullable = false, insertable = false, updatable = false)
	public Estudiante getEstudiante() {
		return this.estudiante;
	}

	public void setEstudiante(Estudiante estudiante) {
		this.estudiante = estudiante;
	}

	@Column(name = "TOTALCREDITOSAPROBADOS", precision = 6, scale = 3)
	public BigDecimal getTotalcreditosaprobados() {
		return this.totalcreditosaprobados;
	}

	public void setTotalcreditosaprobados(BigDecimal totalcreditosaprobados) {
		this.totalcreditosaprobados = totalcreditosaprobados;
	}

	@Column(name = "TOTALCREDITOSCURSADOS", precision = 6, scale = 3)
	public BigDecimal getTotalcreditoscursados() {
		return this.totalcreditoscursados;
	}

	public void setTotalcreditoscursados(BigDecimal totalcreditoscursados) {
		this.totalcreditoscursados = totalcreditoscursados;
	}

	@Column(name = "SITUACIONACADEMICA", length = 80)
	public String getSituacionacademica() {
		return this.situacionacademica;
	}

	public void setSituacionacademica(String situacionacademica) {
		this.situacionacademica = situacionacademica;
	}

	@Column(name = "TOTALCREDITOSCONVALIDADOS", precision = 6, scale = 3)
	public BigDecimal getTotalcreditosconvalidados() {
		return this.totalcreditosconvalidados;
	}

	public void setTotalcreditosconvalidados(BigDecimal totalcreditosconvalidados) {
		this.totalcreditosconvalidados = totalcreditosconvalidados;
	}

	@Column(name = "TOTALCREDITOSCONVALIDADOS2", precision = 6, scale = 3)
	public BigDecimal getTotalcreditosconvalidados2() {
		return this.totalcreditosconvalidados2;
	}

	public void setTotalcreditosconvalidados2(BigDecimal totalcreditosconvalidados2) {
		this.totalcreditosconvalidados2 = totalcreditosconvalidados2;
	}

	@Column(name = "ESTADOPROGRAMAACADEMICO", length = 100)
	public String getEstadoprogramaacademico() {
		return this.estadoprogramaacademico;
	}

	public void setEstadoprogramaacademico(String estadoprogramaacademico) {
		this.estadoprogramaacademico = estadoprogramaacademico;
	}

	@Column(name = "PROMEDIOPONDERADOACUMULADO", nullable = false, precision = 4, scale = 3)
	public BigDecimal getPromedioponderadoacumulado() {
		return this.promedioponderadoacumulado;
	}

	public void setPromedioponderadoacumulado(BigDecimal promedioponderadoacumulado) {
		this.promedioponderadoacumulado = promedioponderadoacumulado;
	}

}
