package com.moisat.persistence.entities;
// Generated Sep 1, 2018 11:44:50 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CentrosDeAyuda generated by hbm2java
 */
@Entity
@Table(name = "CENTROS_DE_AYUDA", schema = "SATFING", uniqueConstraints = @UniqueConstraint(columnNames = "ENCARGADO"))
public class CentrosDeAyuda implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long codigoCentro;
	private Persona persona;
	private String nombre;
	private String correo;

	public CentrosDeAyuda() {
	}

	public CentrosDeAyuda(long codigoCentro, Persona persona) {
		this.codigoCentro = codigoCentro;
		this.persona = persona;
	}

	public CentrosDeAyuda(long codigoCentro, Persona persona, String nombre, String correo) {
		this.codigoCentro = codigoCentro;
		this.persona = persona;
		this.nombre = nombre;
		this.correo = correo;
	}

	@Id

	@Column(name = "CODIGO_CENTRO", unique = true, nullable = false, precision = 10, scale = 0)
	public long getCodigoCentro() {
		return this.codigoCentro;
	}

	public void setCodigoCentro(long codigoCentro) {
		this.codigoCentro = codigoCentro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ENCARGADO", unique = true, nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "NOMBRE", length = 510)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "CORREO")
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

}
