package com.moisat.persistence.entities;
// Generated Aug 30, 2018 5:54:55 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clase generated by hbm2java
 */
@Entity
@Table(name = "CLASE", schema = "SATFING")
public class Clase implements java.io.Serializable {

	private long codigoClase;
	private Asignatura asignatura;
	private Profesor profesor;
	private Set<RegistroClaseEstudiante> registroClaseEstudiantes = new HashSet(0);

	public Clase() {
	}

	public Clase(long codigoClase, Asignatura asignatura, Profesor profesor) {
		this.codigoClase = codigoClase;
		this.asignatura = asignatura;
		this.profesor = profesor;
	}

	public Clase(long codigoClase, Asignatura asignatura, Profesor profesor, Set registroClaseEstudiantes) {
		this.codigoClase = codigoClase;
		this.asignatura = asignatura;
		this.profesor = profesor;
		this.registroClaseEstudiantes = registroClaseEstudiantes;
	}

	@Id

	@Column(name = "CODIGO_CLASE", unique = true, nullable = false, precision = 10, scale = 0)
	public long getCodigoClase() {
		return this.codigoClase;
	}

	public void setCodigoClase(long codigoClase) {
		this.codigoClase = codigoClase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGO_ASIGNATURA", nullable = false)
	public Asignatura getAsignatura() {
		return this.asignatura;
	}

	public void setAsignatura(Asignatura asignatura) {
		this.asignatura = asignatura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGO_PROFESOR", nullable = false)
	public Profesor getProfesor() {
		return this.profesor;
	}

	public void setProfesor(Profesor profesor) {
		this.profesor = profesor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clase")
	public Set<RegistroClaseEstudiante> getRegistroClaseEstudiantes() {
		return this.registroClaseEstudiantes;
	}

	public void setRegistroClaseEstudiantes(Set<RegistroClaseEstudiante> registroClaseEstudiantes) {
		this.registroClaseEstudiantes = registroClaseEstudiantes;
	}

}
