package com.moisat.persistence.entities;
// Generated Aug 30, 2018 5:54:55 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Consejero generated by hbm2java
 */
@Entity
@Table(name = "CONSEJERO", schema = "SATFING", uniqueConstraints = @UniqueConstraint(columnNames = "CODIGO_PERSONA"))
public class Consejero implements java.io.Serializable {

	private ConsejeroId id;
	private Departamento departamento;
	private Persona persona;

	public Consejero() {
	}

	public Consejero(ConsejeroId id, Departamento departamento, Persona persona) {
		this.id = id;
		this.departamento = departamento;
		this.persona = persona;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "departamento", column = @Column(name = "DEPARTAMENTO", nullable = false, length = 510)),
			@AttributeOverride(name = "codigoPersona", column = @Column(name = "CODIGO_PERSONA", unique = true, nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "ciclo", column = @Column(name = "CICLO", length = 40)) })
	public ConsejeroId getId() {
		return this.id;
	}

	public void setId(ConsejeroId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEPARTAMENTO", nullable = false, insertable = false, updatable = false)
	public Departamento getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGO_PERSONA", unique = true, nullable = false, insertable = false, updatable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

}
