package com.moisat.persistence.entities;
// Generated Aug 30, 2018 5:54:55 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Estudiante generated by hbm2java
 */
@Entity
@Table(name = "ESTUDIANTE", schema = "SATFING", uniqueConstraints = @UniqueConstraint(columnNames = "CODIGO_PERSONA"))
public class Estudiante implements java.io.Serializable {

	private long codigoEstudiante;
	private Persona persona;
	private String saber11;
	private Long saber11math;
	private String tipodeadmision;
	private String saber11lenguaje;
	private String nivelclasificacionlenguas;
	private Short asistenciascaps;
	private Short asistenciamath;
	private String nivelclasificacionmath;
	private Set<CarreraEstudiante> carreraEstudiantes = new HashSet(0);
	private Set <RegistroClaseEstudiante>registroClaseEstudiantes = new HashSet(0);
	private Set <ProtocoloAtencion>protocoloAtencions = new HashSet(0);

	public Estudiante() {
	}

	public Estudiante(long codigoEstudiante, Persona persona) {
		this.codigoEstudiante = codigoEstudiante;
		this.persona = persona;
	}

	public Estudiante(long codigoEstudiante, Persona persona, String saber11, Long saber11math, String tipodeadmision,
			String saber11lenguaje, String nivelclasificacionlenguas, Short asistenciascaps, Short asistenciamath,
			String nivelclasificacionmath, Set carreraEstudiantes, Set registroClaseEstudiantes,
			Set protocoloAtencions) {
		this.codigoEstudiante = codigoEstudiante;
		this.persona = persona;
		this.saber11 = saber11;
		this.saber11math = saber11math;
		this.tipodeadmision = tipodeadmision;
		this.saber11lenguaje = saber11lenguaje;
		this.nivelclasificacionlenguas = nivelclasificacionlenguas;
		this.asistenciascaps = asistenciascaps;
		this.asistenciamath = asistenciamath;
		this.nivelclasificacionmath = nivelclasificacionmath;
		this.carreraEstudiantes = carreraEstudiantes;
		this.registroClaseEstudiantes = registroClaseEstudiantes;
		this.protocoloAtencions = protocoloAtencions;
	}

	@Id

	@Column(name = "CODIGO_ESTUDIANTE", unique = true, nullable = false, precision = 15, scale = 0)
	public long getCodigoEstudiante() {
		return this.codigoEstudiante;
	}

	public void setCodigoEstudiante(long codigoEstudiante) {
		this.codigoEstudiante = codigoEstudiante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGO_PERSONA", unique = true, nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "SABER11", length = 40)
	public String getSaber11() {
		return this.saber11;
	}

	public void setSaber11(String saber11) {
		this.saber11 = saber11;
	}

	@Column(name = "SABER11MATH", precision = 10, scale = 0)
	public Long getSaber11math() {
		return this.saber11math;
	}

	public void setSaber11math(Long saber11math) {
		this.saber11math = saber11math;
	}

	@Column(name = "TIPODEADMISION", length = 5)
	public String getTipodeadmision() {
		return this.tipodeadmision;
	}

	public void setTipodeadmision(String tipodeadmision) {
		this.tipodeadmision = tipodeadmision;
	}

	@Column(name = "SABER11LENGUAJE", length = 40)
	public String getSaber11lenguaje() {
		return this.saber11lenguaje;
	}

	public void setSaber11lenguaje(String saber11lenguaje) {
		this.saber11lenguaje = saber11lenguaje;
	}

	@Column(name = "NIVELCLASIFICACIONLENGUAS", length = 20)
	public String getNivelclasificacionlenguas() {
		return this.nivelclasificacionlenguas;
	}

	public void setNivelclasificacionlenguas(String nivelclasificacionlenguas) {
		this.nivelclasificacionlenguas = nivelclasificacionlenguas;
	}

	@Column(name = "ASISTENCIASCAPS", precision = 3, scale = 0)
	public Short getAsistenciascaps() {
		return this.asistenciascaps;
	}

	public void setAsistenciascaps(Short asistenciascaps) {
		this.asistenciascaps = asistenciascaps;
	}

	@Column(name = "ASISTENCIAMATH", precision = 3, scale = 0)
	public Short getAsistenciamath() {
		return this.asistenciamath;
	}

	public void setAsistenciamath(Short asistenciamath) {
		this.asistenciamath = asistenciamath;
	}

	@Column(name = "NIVELCLASIFICACIONMATH", length = 20)
	public String getNivelclasificacionmath() {
		return this.nivelclasificacionmath;
	}

	public void setNivelclasificacionmath(String nivelclasificacionmath) {
		this.nivelclasificacionmath = nivelclasificacionmath;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estudiante")
	public Set<CarreraEstudiante> getCarreraEstudiantes() {
		return this.carreraEstudiantes;
	}

	public void setCarreraEstudiantes(Set<CarreraEstudiante> carreraEstudiantes) {
		this.carreraEstudiantes = carreraEstudiantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estudiante")
	public Set<RegistroClaseEstudiante> getRegistroClaseEstudiantes() {
		return this.registroClaseEstudiantes;
	}

	public void setRegistroClaseEstudiantes(Set<RegistroClaseEstudiante> registroClaseEstudiantes) {
		this.registroClaseEstudiantes = registroClaseEstudiantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estudiante")
	public Set<ProtocoloAtencion> getProtocoloAtencions() {
		return this.protocoloAtencions;
	}

	public void setProtocoloAtencions(Set<ProtocoloAtencion> protocoloAtencions) {
		this.protocoloAtencions = protocoloAtencions;
	}

}
