package com.moisat.persistence.entities;
// Generated Sep 1, 2018 11:44:50 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Facultad generated by hbm2java
 */
@Entity
@Table(name = "FACULTAD", schema = "SATFING")
public class Facultad implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idFacultad;
	private String nombreFacultad;
	private Set<Departamento> departamentos = new HashSet<Departamento>(0);
	private Set<Carrera> carreras = new HashSet<Carrera>(0);

	public Facultad() {
	}

	public Facultad(String idFacultad, String nombreFacultad) {
		this.idFacultad = idFacultad;
		this.nombreFacultad = nombreFacultad;
	}

	public Facultad(String idFacultad, String nombreFacultad, Set<Departamento> departamentos, Set<Carrera> carreras) {
		this.idFacultad = idFacultad;
		this.nombreFacultad = nombreFacultad;
		this.departamentos = departamentos;
		this.carreras = carreras;
	}

	@Id

	@Column(name = "ID_FACULTAD", unique = true, nullable = false, length = 510)
	public String getIdFacultad() {
		return this.idFacultad;
	}

	public void setIdFacultad(String idFacultad) {
		this.idFacultad = idFacultad;
	}

	@Column(name = "NOMBRE_FACULTAD", nullable = false, length = 510)
	public String getNombreFacultad() {
		return this.nombreFacultad;
	}

	public void setNombreFacultad(String nombreFacultad) {
		this.nombreFacultad = nombreFacultad;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "facultad")
	public Set<Departamento> getDepartamentos() {
		return this.departamentos;
	}

	public void setDepartamentos(Set<Departamento> departamentos) {
		this.departamentos = departamentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "facultad")
	public Set<Carrera> getCarreras() {
		return this.carreras;
	}

	public void setCarreras(Set<Carrera> carreras) {
		this.carreras = carreras;
	}

}
