package com.moisat.persistence.entities;
// Generated Aug 30, 2018 5:54:55 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name = "PERSONA", schema = "SATFING")
public class Persona implements java.io.Serializable {

	private long codigoPersona;
	private String nombres;
	private String apellido;
	private long identificacion;
	private Short tipoidentificacion;
	private String genero;
	private String direccion;
	private String correo;
	private Long telefono;
	private String apellido2;
	private Set<Actor> actors = new HashSet(0);
	private Set<Departamento> departamentos = new HashSet(0);
	private Set<Carrera> carreras = new HashSet(0);
	private Set <Estudiante>estudiantes = new HashSet(0);
	private Set <Profesor>profesors = new HashSet(0);
	private Set<CentrosDeAyuda> centrosDeAyudas = new HashSet(0);
	private Set<Consejero> consejeros = new HashSet(0);

	public Persona() {
	}

	public Persona(long codigoPersona, long identificacion) {
		this.codigoPersona = codigoPersona;
		this.identificacion = identificacion;
	}

	public Persona(long codigoPersona, String nombres, String apellido, long identificacion, Short tipoidentificacion,
			String genero, String direccion, String correo, Long telefono, String apellido2, Set actors,
			Set departamentos, Set carreras, Set estudiantes, Set profesors, Set centrosDeAyudas, Set consejeros) {
		this.codigoPersona = codigoPersona;
		this.nombres = nombres;
		this.apellido = apellido;
		this.identificacion = identificacion;
		this.tipoidentificacion = tipoidentificacion;
		this.genero = genero;
		this.direccion = direccion;
		this.correo = correo;
		this.telefono = telefono;
		this.apellido2 = apellido2;
		this.actors = actors;
		this.departamentos = departamentos;
		this.carreras = carreras;
		this.estudiantes = estudiantes;
		this.profesors = profesors;
		this.centrosDeAyudas = centrosDeAyudas;
		this.consejeros = consejeros;
	}

	@Id

	@Column(name = "CODIGO_PERSONA", unique = true, nullable = false, precision = 10, scale = 0)
	public long getCodigoPersona() {
		return this.codigoPersona;
	}

	public void setCodigoPersona(long codigoPersona) {
		this.codigoPersona = codigoPersona;
	}

	@Column(name = "NOMBRES", length = 45)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "APELLIDO", length = 45)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Column(name = "IDENTIFICACION", nullable = false, precision = 16, scale = 0)
	public long getIdentificacion() {
		return this.identificacion;
	}

	public void setIdentificacion(long identificacion) {
		this.identificacion = identificacion;
	}

	@Column(name = "TIPOIDENTIFICACION", precision = 3, scale = 0)
	public Short getTipoidentificacion() {
		return this.tipoidentificacion;
	}

	public void setTipoidentificacion(Short tipoidentificacion) {
		this.tipoidentificacion = tipoidentificacion;
	}

	@Column(name = "GENERO", length = 20)
	public String getGenero() {
		return this.genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}

	@Column(name = "DIRECCION", length = 510)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "CORREO", length = 510)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "TELEFONO", precision = 12, scale = 0)
	public Long getTelefono() {
		return this.telefono;
	}

	public void setTelefono(Long telefono) {
		this.telefono = telefono;
	}

	@Column(name = "APELLIDO2", length = 90)
	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<Actor> getActors() {
		return this.actors;
	}

	public void setActors(Set<Actor> actors) {
		this.actors = actors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<Departamento> getDepartamentos() {
		return this.departamentos;
	}

	public void setDepartamentos(Set<Departamento> departamentos) {
		this.departamentos = departamentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<Carrera> getCarreras() {
		return this.carreras;
	}

	public void setCarreras(Set<Carrera> carreras) {
		this.carreras = carreras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<Estudiante> getEstudiantes() {
		return this.estudiantes;
	}

	public void setEstudiantes(Set<Estudiante> estudiantes) {
		this.estudiantes = estudiantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<Profesor> getProfesors() {
		return this.profesors;
	}

	public void setProfesors(Set<Profesor> profesors) {
		this.profesors = profesors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<CentrosDeAyuda> getCentrosDeAyudas() {
		return this.centrosDeAyudas;
	}

	public void setCentrosDeAyudas(Set<CentrosDeAyuda> centrosDeAyudas) {
		this.centrosDeAyudas = centrosDeAyudas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<Consejero> getConsejeros() {
		return this.consejeros;
	}

	public void setConsejeros(Set<Consejero> consejeros) {
		this.consejeros = consejeros;
	}

}
