package com.moisat.persistence.entities;
// Generated Aug 30, 2018 5:54:55 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProtocoloAtencion generated by hbm2java
 */
@Entity
@Table(name = "PROTOCOLO_ATENCION", schema = "SATFING")
public class ProtocoloAtencion implements java.io.Serializable {

	private long codigoProtocolo;
	private Estudiante estudiante;
	private Alerta alerta;
	private Set<Intervencion> intervencions = new HashSet(0);

	public ProtocoloAtencion() {
	}

	public ProtocoloAtencion(long codigoProtocolo, Estudiante estudiante, Alerta alerta) {
		this.codigoProtocolo = codigoProtocolo;
		this.estudiante = estudiante;
		this.alerta = alerta;
	}

	public ProtocoloAtencion(long codigoProtocolo, Estudiante estudiante, Alerta alerta, Set intervencions) {
		this.codigoProtocolo = codigoProtocolo;
		this.estudiante = estudiante;
		this.alerta = alerta;
		this.intervencions = intervencions;
	}

	@Id

	@Column(name = "CODIGO_PROTOCOLO", unique = true, nullable = false, precision = 10, scale = 0)
	public long getCodigoProtocolo() {
		return this.codigoProtocolo;
	}

	public void setCodigoProtocolo(long codigoProtocolo) {
		this.codigoProtocolo = codigoProtocolo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGO_ESTUDIANTE", nullable = false)
	public Estudiante getEstudiante() {
		return this.estudiante;
	}

	public void setEstudiante(Estudiante estudiante) {
		this.estudiante = estudiante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGO_ALERTA", nullable = false)
	public Alerta getAlerta() {
		return this.alerta;
	}

	public void setAlerta(Alerta alerta) {
		this.alerta = alerta;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "protocoloAtencion")
	public Set<Intervencion> getIntervencions() {
		return this.intervencions;
	}

	public void setIntervencions(Set<Intervencion> intervencions) {
		this.intervencions = intervencions;
	}

}
