package com.moisat.persistence.entities;
// Generated Aug 30, 2018 5:54:55 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RegistroClaseEstudiante generated by hbm2java
 */
@Entity
@Table(name = "REGISTRO_CLASE_ESTUDIANTE", schema = "SATFING")
public class RegistroClaseEstudiante implements java.io.Serializable {

	private long codigoRegistro;
	private Estudiante estudiante;
	private Clase clase;
	private Long cicloLectivo;
	private BigDecimal calificacion;

	public RegistroClaseEstudiante() {
	}

	public RegistroClaseEstudiante(long codigoRegistro, Estudiante estudiante, Clase clase) {
		this.codigoRegistro = codigoRegistro;
		this.estudiante = estudiante;
		this.clase = clase;
	}

	public RegistroClaseEstudiante(long codigoRegistro, Estudiante estudiante, Clase clase, Long cicloLectivo,
			BigDecimal calificacion) {
		this.codigoRegistro = codigoRegistro;
		this.estudiante = estudiante;
		this.clase = clase;
		this.cicloLectivo = cicloLectivo;
		this.calificacion = calificacion;
	}

	@Id

	@Column(name = "CODIGO_REGISTRO", unique = true, nullable = false, precision = 10, scale = 0)
	public long getCodigoRegistro() {
		return this.codigoRegistro;
	}

	public void setCodigoRegistro(long codigoRegistro) {
		this.codigoRegistro = codigoRegistro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGO_ESTUDIANTE", nullable = false)
	public Estudiante getEstudiante() {
		return this.estudiante;
	}

	public void setEstudiante(Estudiante estudiante) {
		this.estudiante = estudiante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODIGO_CLASE", nullable = false)
	public Clase getClase() {
		return this.clase;
	}

	public void setClase(Clase clase) {
		this.clase = clase;
	}

	@Column(name = "CICLO_LECTIVO", precision = 10, scale = 0)
	public Long getCicloLectivo() {
		return this.cicloLectivo;
	}

	public void setCicloLectivo(Long cicloLectivo) {
		this.cicloLectivo = cicloLectivo;
	}

	@Column(name = "CALIFICACION", precision = 4, scale = 3)
	public BigDecimal getCalificacion() {
		return this.calificacion;
	}

	public void setCalificacion(BigDecimal calificacion) {
		this.calificacion = calificacion;
	}

}
